---
- hosts: select
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    # Install pre-requisites
    - include: tasks/nodeconfig.yml
    - include: tasks/prerequisites.yml

  handlers:
    - name: reload chronyd
      service: name=chronyd state=restarted

    - name: yum upgrade
      yum: name=* state=latest
