--- # Installation of packages here 
- name: Yum package install
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - chrony
  
- lineinfile:
    path: /etc/chrony.conf
    insertafter: '^#allow\s(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{2})'
    line: 'allow 10.0.0.0/24'
    state: present 
  when: ansible_hostname == "controller"
  notify:
  - reload chronyd
