--- # Installation of packages here 
- name: Install additional repository
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - centos-release-openstack-pike
  notify:
  - yum upgrade

- meta: flush_handlers #run yum-upgrade before installing the packages below

- name: Yum package install
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - chrony
    - python-openstackclient
    - openstack-selinux
  
- name: configure chrony on controller
  lineinfile:
    path: /etc/chrony.conf
    insertafter: '^#allow\s(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{2})'
    line: 'allow 10.0.0.0/24'
    state: present 
  when: ansible_hostname == "controller"
  notify:
  - reload chronyd

- name: configure chrony on other nodes remove default ntp servers
  replace:
    path: /etc/chrony.conf
    regexp: '^(.*?)server\s\d\.\w+\.\pool.*?\s\iburst.?$'
    replace: '\1'
  when: ansible_hostname != "controller"

- name: configure chrony on other nodes add controller as ntp server and reload chrony
  lineinfile:
    path: /etc/chrony.conf
    insertafter: '^#\sPlease\sconsider.*$'
    line: 'server controller iburst'
    state: present
  when: ansible_hostname != "controller"
  notify:
  - reload chronyd
   

