- name: Configure hosts file
  blockinfile:
    path: /etc/hosts
    state: present
    block: | 
      10.0.0.11   controller
      10.0.0.31   compute
      10.0.0.41   block
      10.0.0.51   object1
      10.0.0.52   object2
      10.0.0.61   controlmanager

- name: Upgrade ALL packages
  yum: name=* state=latest

- name: Accept all packets from 10.0.0.0/24 network
  firewalld:
    zone: public
    rich_rule: 'rule family="ipv4" source address="10.0.0.0/24" accept'
    permanent: true
    state: enabled
    immediate: true
  




  
