- name: Configure hosts file
  blockinfile:
    path: /etc/hosts
    state: present
    block: | 
      10.0.0.11   controller
      10.0.0.31   compute
      10.0.0.41   block
      10.0.0.51   object1
      10.0.0.52   object2

- name: Upgrade ALL packages
  yum: name=* state=latest

  
